---
language: android
android:
  components:
    - extra-android-m2repository
    - build-tools-20.0.0
    - build-tools-22.0.0
    - android-21
    - android-22
    - sys-img-armeabi-v7a-android-21

env:
    - TERM=dumb

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -skin 480x800 -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82
  - cd examples/android/android-studio

script: for subdir in $(ls -d */); do cd $subdir && (./gradlew connectedCheck || exit 1) && cd ..; done

branches:
  only:
  - android-gradle
notifications:
  email:
  - cukes-devs@googlegroups.com
  irc:
  - irc.freenode.org#cucumber
