---
language: android
android:
  components:
    - extra-android-m2repository
    - build-tools-22.0.0
    - android-22
    - sys-img-armeabi-v7a-android-21

env:
    - TERM=dumb

before_script:
  - cd examples/android/android-studio
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -skin 480x800 -dpi-device 240 -no-boot-anim -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82
  - adb install -r android_emulator_hacks-debug.apk
  - adb shell pm grant no.finn.android_emulator_hacks android.permission.SET_ANIMATION_SCALE
  - adb shell am start -n no.finn.android_emulator_hacks/no.finn.android_emulator_hacks.HackActivity

script: for subdir in $(ls -d */); do cd $subdir && ./gradlew connectedCheck && cd .. || cd .. && gradle_failed=1; done && expr ${gradle_failed?0} = 0

branches:
  only:
  - android-gradle
notifications:
  email:
  - cukes-devs@googlegroups.com
  irc:
  - irc.freenode.org#cucumber
